# Generated by Django 6.0.6 on 2026-06-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('preco_gasolina', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('preco_etanol', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('preco_diesel', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comodidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('conveniencia', 'Conveniencia'), ('farmacia', 'Farmacia'), ('restaurante', 'Restaurante'), ('loja', 'Loja')], max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comodidades', to='Abasteceaiapp.posto')),
            ],
        ),
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gasolina', 'Gasolina Comum'), ('aditivada', 'Gasolina Aditivada'), ('etanol', 'Etanol'), ('diesel', 'Diesel S-10')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='Abasteceaiapp.posto')),
            ],
        ),
    ]
