# Generated by Django 6.0.6 on 2026-06-27 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abasteceaiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='preco',
            name='tipo',
        ),
        migrations.AddField(
            model_name='preco',
            name='tipo_combustivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='Abasteceaiapp.tipocombustivel'),
            preserve_default=False,
        ),
    ]
