# Generated by Django 6.0.6 on 2026-07-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abasteceaiapp', '0002_tipocombustivel_remove_preco_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
    ]
